services:
  hottake-hub-backend:
    image: ${DOCKER_REGISTRY-}hottakehubbackend
    depends_on:
      - hottake-hub-sqlserver
    build:
      context: .
      dockerfile: HotTake-Hub-Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HotTakeHub;User Id=sa;Password=DevPassword123!
  
  hottake-hub-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "DevPassword123!"
